import fs from 'fs';

const content = fs.readFileSync('./src/App.tsx', 'utf8');

const newTrans = {
  es: {
    med_title: "Medicación",
    med_desc: "• Suspender Aspirina u otros inhibidores de la agregación plaquetaria como Adiro®, Iscover®, Disgren®, Tiklid®, Plavix® entre 3 y 8 días antes del examen – consulte con su médico si tiene dudas al respecto.\n• En caso de tomar Sintrom® u otro anticoagulante (Xarelto®, Pradaxa®…) debe consultar con su médico para valorar su suspensión o sustitución.\n• En caso de padecer patología cardíaca: Traiga el electrocardiograma, ecocardiograma y las indicaciones de su cardiólogo. AVISAR SI SE REQUIERE PROFILAXIS ANTIBIÓTICA.\n• Hierro oral, suspender 7 días antes de la colonoscopia.\n• NO es necesario suspender otros medicamentos – tomar hasta 12 horas antes de la prueba.",
    med_narrative: "Medicación. Debe suspender Aspirina u otros inhibidores de la agregación plaquetaria como Adiro, Iscover, Disgren, Tiklid o Plavix entre 3 y 8 días antes del examen. Consulte con su médico si tiene dudas. En caso de tomar Sintrom u otro anticoagulante como Xarelto o Pradaxa, debe consultar con su médico para valorar su suspensión o sustitución. En caso de padecer patología cardíaca, traiga el electrocardiograma, ecocardiograma y las indicaciones de su cardiólogo. Avise si se requiere profilaxis antibiótica. El hierro oral debe suspenderse 7 días antes de la colonoscopia. No es necesario suspender otros medicamentos, puede tomarlos hasta 12 horas antes de la prueba.",
    imp_title: "Importante",
    imp_desc: "• No beba alcohol, leche, o nada de color rojo o morado (por ejemplo, zumo de frutos rojos) u otras bebidas que contengan pulpa.\n• No coma mientras toma Pleinvue® y hasta después del procedimiento clínico.\n• No podrá conducir el día de la colonoscopia ni manejar maquinaria peligrosa.\n• TRAER LOS CONSENTIMIENTOS DE COLONOSCOPIA Y SEDACIÓN FIRMADOS.\n• Acuda acompañado a la exploración con alguien que pueda conducir o auxiliarle en su regreso a casa.\n• Existe la posibilidad de que, en caso de realizar intervenciones terapéuticas, como extracción de pólipos, sea necesario que cancele sus compromisos el día siguiente, o podría necesitar quedarse en vigilancia durante 24 horas (esta situación es raramente necesaria).",
    imp_narrative: "Importante. No beba alcohol, leche, o nada de color rojo o morado, como zumo de frutos rojos, u otras bebidas que contengan pulpa. No coma mientras toma Pleinvue y hasta después del procedimiento clínico. No podrá conducir el día de la colonoscopia ni manejar maquinaria peligrosa. Recuerde traer los consentimientos de colonoscopia y sedación firmados. Acuda acompañado a la exploración con alguien que pueda conducir o auxiliarle en su regreso a casa. Existe la posibilidad de que, en caso de realizar intervenciones terapéuticas como extracción de pólipos, sea necesario que cancele sus compromisos el día siguiente, o podría necesitar quedarse en vigilancia durante 24 horas, aunque esta situación es raramente necesaria."
  },
  en: {
    med_title: "Medication",
    med_desc: "• Suspend Aspirin or other platelet aggregation inhibitors like Adiro®, Iscover®, Disgren®, Tiklid®, Plavix® 3 to 8 days before the exam – consult your doctor if in doubt.\n• If taking Sintrom® or another anticoagulant (Xarelto®, Pradaxa®...), consult your doctor to assess its suspension or substitution.\n• If you have heart disease: Bring your electrocardiogram, echocardiogram, and your cardiologist's instructions. NOTIFY IF ANTIBIOTIC PROPHYLAX IS REQUIRED.\n• Oral iron, suspend 7 days before the colonoscopy.\n• It is NOT necessary to suspend other medications – take up to 12 hours before the test.",
    med_narrative: "Medication. You must suspend Aspirin or other platelet aggregation inhibitors like Adiro, Iscover, Disgren, Tiklid, or Plavix between 3 and 8 days before the exam. Consult your doctor if you have doubts. If you take Sintrom or another anticoagulant like Xarelto or Pradaxa, you must consult your doctor to assess its suspension or substitution. If you have heart disease, bring your electrocardiogram, echocardiogram, and your cardiologist's instructions. Notify if antibiotic prophylaxis is required. Oral iron must be suspended 7 days before the colonoscopy. It is not necessary to suspend other medications, you can take them up to 12 hours before the test.",
    imp_title: "Important",
    imp_desc: "• Do not drink alcohol, milk, or anything red or purple (e.g., berry juice) or other drinks containing pulp.\n• Do not eat while taking Pleinvue® and until after the clinical procedure.\n• You will not be able to drive on the day of the colonoscopy or operate dangerous machinery.\n• BRING THE SIGNED COLONOSCOPY AND SEDATION CONSENTS.\n• Come accompanied to the examination by someone who can drive or assist you on your return home.\n• There is a possibility that, in case of therapeutic interventions, such as polyp removal, you may need to cancel your commitments the next day, or you might need to stay under observation for 24 hours (this situation is rarely necessary).",
    imp_narrative: "Important. Do not drink alcohol, milk, or anything red or purple, such as berry juice, or other drinks containing pulp. Do not eat while taking Pleinvue and until after the clinical procedure. You will not be able to drive on the day of the colonoscopy or operate dangerous machinery. Remember to bring the signed colonoscopy and sedation consents. Come accompanied to the examination by someone who can drive or assist you on your return home. There is a possibility that, in case of therapeutic interventions such as polyp removal, you may need to cancel your commitments the next day, or you might need to stay under observation for 24 hours, although this situation is rarely necessary."
  },
  fr: {
    med_title: "Médicaments",
    med_desc: "• Suspendre l'Aspirine ou autres inhibiteurs de l'agrégation plaquettaire comme Adiro®, Iscover®, Disgren®, Tiklid®, Plavix® 3 à 8 jours avant l'examen – consultez votre médecin en cas de doute.\n• Si vous prenez du Sintrom® ou un autre anticoagulant (Xarelto®, Pradaxa®...), consultez votre médecin pour évaluer sa suspension ou son remplacement.\n• En cas de maladie cardiaque : Apportez votre électrocardiogramme, échocardiogramme et les instructions de votre cardiologue. PRÉVENIR SI UNE PROPHYLAXIE ANTIBIOTIQUE EST REQUISE.\n• Fer oral, suspendre 7 jours avant la coloscopie.\n• Il n'est PAS nécessaire de suspendre d'autres médicaments – prendre jusqu'à 12 heures avant le test.",
    med_narrative: "Médicaments. Vous devez suspendre l'Aspirine ou autres inhibiteurs de l'agrégation plaquettaire comme Adiro, Iscover, Disgren, Tiklid ou Plavix entre 3 et 8 jours avant l'examen. Consultez votre médecin en cas de doute. Si vous prenez du Sintrom ou un autre anticoagulant comme Xarelto ou Pradaxa, vous devez consulter votre médecin pour évaluer sa suspension ou son remplacement. En cas de maladie cardiaque, apportez votre électrocardiogramme, échocardiogramme et les instructions de votre cardiologue. Prévenez si une prophylaxie antibiotique est requise. Le fer oral doit être suspendu 7 jours avant la coloscopie. Il n'est pas nécessaire de suspendre d'autres médicaments, vous pouvez les prendre jusqu'à 12 heures avant le test.",
    imp_title: "Important",
    imp_desc: "• Ne buvez pas d'alcool, de lait, ou quoi que ce soit de rouge ou violet (par exemple, jus de fruits rouges) ou d'autres boissons contenant de la pulpe.\n• Ne mangez pas pendant la prise de Pleinvue® et jusqu'après la procédure clinique.\n• Vous ne pourrez pas conduire le jour de la coloscopie ni utiliser de machines dangereuses.\n• APPORTER LES CONSENTEMENTS DE COLOSCOPIE ET DE SÉDATION SIGNÉS.\n• Venez accompagné à l'examen par quelqu'un qui peut conduire ou vous aider à rentrer chez vous.\n• Il est possible que, en cas d'interventions thérapeutiques, comme l'ablation de polypes, vous deviez annuler vos engagements le lendemain, ou vous pourriez avoir besoin de rester en observation pendant 24 heures (cette situation est rarement nécessaire).",
    imp_narrative: "Important. Ne buvez pas d'alcool, de lait, ou quoi que ce soit de rouge ou violet, comme du jus de fruits rouges, ou d'autres boissons contenant de la pulpe. Ne mangez pas pendant la prise de Pleinvue et jusqu'après la procédure clinique. Vous ne pourrez pas conduire le jour de la coloscopie ni utiliser de machines dangereuses. N'oubliez pas d'apporter les consentements de coloscopie et de sédation signés. Venez accompagné à l'examen par quelqu'un qui peut conduire ou vous aider à rentrer chez vous. Il est possible que, en cas d'interventions thérapeutiques comme l'ablation de polypes, vous deviez annuler vos engagements le lendemain, ou vous pourriez avoir besoin de rester en observation pendant 24 heures, bien que cette situation soit rarement nécessaire."
  },
  de: {
    med_title: "Medikamente",
    med_desc: "• Setzen Sie Aspirin oder andere Thrombozytenaggregationshemmer wie Adiro®, Iscover®, Disgren®, Tiklid®, Plavix® 3 bis 8 Tage vor der Untersuchung ab – konsultieren Sie im Zweifelsfall Ihren Arzt.\n• Wenn Sie Sintrom® oder ein anderes Antikoagulans (Xarelto®, Pradaxa®...) einnehmen, konsultieren Sie Ihren Arzt, um das Absetzen oder Ersetzen zu beurteilen.\n• Bei Herzerkrankungen: Bringen Sie Ihr Elektrokardiogramm, Echokardiogramm und die Anweisungen Ihres Kardiologen mit. MELDEN SIE, WENN EINE ANTIBIOTIKAPROPHYLAXE ERFORDERLICH IST.\n• Orales Eisen 7 Tage vor der Koloskopie absetzen.\n• Es ist NICHT notwendig, andere Medikamente abzusetzen – bis zu 12 Stunden vor dem Test einnehmen.",
    med_narrative: "Medikamente. Sie müssen Aspirin oder andere Thrombozytenaggregationshemmer wie Adiro, Iscover, Disgren, Tiklid oder Plavix zwischen 3 und 8 Tagen vor der Untersuchung absetzen. Konsultieren Sie im Zweifelsfall Ihren Arzt. Wenn Sie Sintrom oder ein anderes Antikoagulans wie Xarelto oder Pradaxa einnehmen, müssen Sie Ihren Arzt konsultieren, um das Absetzen oder Ersetzen zu beurteilen. Bei Herzerkrankungen bringen Sie Ihr Elektrokardiogramm, Echokardiogramm und die Anweisungen Ihres Kardiologen mit. Melden Sie, wenn eine Antibiotikaprophylaxe erforderlich ist. Orales Eisen muss 7 Tage vor der Koloskopie abgesetzt werden. Es ist nicht notwendig, andere Medikamente abzusetzen, Sie können diese bis zu 12 Stunden vor dem Test einnehmen.",
    imp_title: "Wichtig",
    imp_desc: "• Trinken Sie keinen Alkohol, keine Milch oder irgendetwas Rotes oder Lila (z. B. Beerensaft) oder andere Getränke mit Fruchtfleisch.\n• Essen Sie nicht während der Einnahme von Pleinvue® und bis nach dem klinischen Eingriff.\n• Sie dürfen am Tag der Koloskopie nicht Auto fahren oder gefährliche Maschinen bedienen.\n• BRINGEN SIE DIE UNTERSCHRIEBENEN EINWILLIGUNGEN FÜR KOLOSKOPIE UND SEDIERUNG MIT.\n• Kommen Sie in Begleitung zur Untersuchung mit jemandem, der fahren oder Ihnen bei der Heimkehr helfen kann.\n• Es besteht die Möglichkeit, dass Sie im Falle von therapeutischen Eingriffen, wie z. B. Polypenentfernung, Ihre Verpflichtungen am nächsten Tag absagen müssen, oder Sie müssen möglicherweise 24 Stunden zur Beobachtung bleiben (diese situation ist selten erforderlich).",
    imp_narrative: "Wichtig. Trinken Sie keinen Alkohol, keine Milch oder irgendetwas Rotes oder Lila, wie z. B. Beerensaft, oder andere Getränke mit Fruchtfleisch. Essen Sie nicht während der Einnahme von Pleinvue und bis nach dem klinischen Eingriff. Sie dürfen am Tag der Koloskopie nicht Auto fahren oder gefährliche Maschinen bedienen. Denken Sie daran, die unterschriebenen Einwilligungen für Koloskopie und Sedierung mitzubringen. Kommen Sie in Begleitung zur Untersuchung mit jemandem, der fahren oder Ihnen bei der Heimkehr helfen kann. Es besteht die Möglichkeit, dass Sie im Falle von therapeutischen Eingriffen wie z. B. Polypenentfernung Ihre Verpflichtungen am nächsten Tag absagen müssen, oder Sie müssen möglicherweise 24 Stunden zur Beobachtung bleiben, obwohl diese Situation selten erforderlich ist."
  },
  it: {
    med_title: "Farmaci",
    med_desc: "• Sospendere Aspirina o altri inibitori dell'aggregazione piastrinica come Adiro®, Iscover®, Disgren®, Tiklid®, Plavix® tra 3 e 8 giorni prima dell'esame – consulti il medico in caso di dubbi.\n• In caso di assunzione di Sintrom® o altro anticoagulante (Xarelto®, Pradaxa®…), consultare il medico per valutarne la sospensione o sostituzione.\n• In caso di patologia cardiaca: Portare l'elettrocardiogramma, l'ecocardiogramma e le indicazioni del cardiologo. AVVISARE SE È RICHIESTA PROFILASSI ANTIBIOTICA.\n• Ferro orale, sospendere 7 giorni prima della colonscopia.\n• NON è necessario sospendere altri farmaci – assumere fino a 12 ore prima del test.",
    med_narrative: "Farmaci. Deve sospendere Aspirina o altri inibitori dell'aggregazione piastrinica come Adiro, Iscover, Disgren, Tiklid o Plavix tra 3 e 8 giorni prima dell'esame. Consulti il medico in caso di dubbi. In caso di assunzione di Sintrom o altro anticoagulante come Xarelto o Pradaxa, deve consultare il medico per valutarne la sospensione o sostituzione. In caso di patologia cardiaca, portare l'elettrocardiogramma, l'ecocardiogramma e le indicazioni del cardiologo. Avvisare se è richiesta profilassi antibiotica. Il ferro orale deve essere sospeso 7 giorni prima della colonscopia. Non è necessario sospendere altri farmaci, può assumerli fino a 12 ore prima del test.",
    imp_title: "Importante",
    imp_desc: "• Non beva alcol, latte, o nulla di colore rosso o viola (ad esempio, succo di frutti rossi) o altre bevande contenenti polpa.\n• Non mangi mentre assume Pleinvue® e fino a dopo la procedura clinica.\n• Non potrà guidare il giorno della colonscopia né manovrare macchinari pericolosi.\n• PORTARE I CONSENSI DI COLONSCOPIA E SEDAZIONE FIRMATI.\n• Si rechi all'esame accompagnato da qualcuno che possa guidare o assisterla nel ritorno a casa.\n• Esiste la possibilità che, in caso di interventi terapeutici, come l'asportazione di polipi, sia necessario annullare i propri impegni il giorno successivo, o potrebbe essere necessario rimanere in osservazione per 24 ore (questa situazione è raramente necessaria).",
    imp_narrative: "Importante. Non beva alcol, latte, o nulla di colore rosso o viola, come succo di frutti rossi, o altre bevande contenenti polpa. Non mangi mentre assume Pleinvue e fino a dopo la procedura clinica. Non potrà guidare il giorno della colonscopia né manovrare macchinari pericolosi. Ricordi di portare i consensi di colonscopia e sedazione firmati. Si rechi all'esame accompagnato da qualcuno che possa guidare o assisterla nel ritorno a casa. Esiste la possibilità che, in caso di interventi terapeutici come l'asportazione di polipi, sia necessario annullare i propri impegni il giorno successivo, o potrebbe essere necessario rimanere in osservazione per 24 ore, sebbene questa situazione sia raramente necessaria."
  },
  pt: {
    med_title: "Medicação",
    med_desc: "• Suspender Aspirina ou outros inibidores da agregação plaquetária como Adiro®, Iscover®, Disgren®, Tiklid®, Plavix® entre 3 e 8 dias antes do exame – consulte o seu médico se tiver dúvidas.\n• No caso de tomar Sintrom® ou outro anticoagulante (Xarelto®, Pradaxa®…), deve consultar o seu médico para avaliar a sua suspensão ou substituição.\n• Em caso de patologia cardíaca: Traga o eletrocardiograma, ecocardiograma e as indicações do seu cardiologista. AVISAR SE FOR NECESSÁRIA PROFILAXIA ANTIBIÓTICA.\n• Ferro oral, suspender 7 dias antes da colonoscopia.\n• NÃO é necessário suspender outros medicamentos – tomar até 12 horas antes do teste.",
    med_narrative: "Medicação. Deve suspender Aspirina ou outros inibidores da agregação plaquetária como Adiro, Iscover, Disgren, Tiklid ou Plavix entre 3 e 8 dias antes do exame. Consulte o seu médico se tiver dúvidas. No caso de tomar Sintrom ou outro anticoagulante como Xarelto ou Pradaxa, deve consultar o seu médico para avaliar a sua suspensão ou substituição. Em caso de patologia cardíaca, traga o eletrocardiograma, ecocardiograma e as indicações do seu cardiologista. Avise se for necessária profilaxia antibiótica. O ferro oral deve ser suspenso 7 dias antes da colonoscopia. Não é necessário suspender outros medicamentos, pode tomá-los até 12 horas antes do teste.",
    imp_title: "Importante",
    imp_desc: "• Não beba álcool, leite, ou nada de cor vermelha ou roxa (por exemplo, sumo de frutos vermelhos) ou outras bebidas que contenham polpa.\n• Não coma enquanto toma Pleinvue® e até depois do procedimento clínico.\n• Não poderá conduzir no dia da colonoscopia nem manusear máquinas perigosas.\n• TRAZER OS CONSENTIMENTOS DE COLONOSCOPIA E SEDAÇÃO ASSINADOS.\n• Dirija-se ao exame acompanhado por alguém que possa conduzir ou auxiliá-lo no regresso a casa.\n• Existe a possibilidade de que, em caso de intervenções terapêuticas, como extração de pólipos, seja necessário cancelar os seus compromissos no dia seguinte, ou poderá precisar de ficar em vigilância durante 24 horas (esta situação é raramente necessária).",
    imp_narrative: "Importante. Não beba álcool, leite, ou nada de cor vermelha ou roxa, como sumo de frutos vermelhos, ou outras bebidas que contenham polpa. Não coma enquanto toma Pleinvue e até depois do procedimento clínico. Não poderá conduzir no dia da colonoscopia nem manusear máquinas perigosas. Lembre-se de trazer os consentimentos de colonoscopia e sedação assinados. Dirija-se ao exame acompanhado por alguém que possa conduzir ou auxiliá-lo no regresso a casa. Existe a possibilidade de que, em caso de intervenções terapêuticas como extração de pólipos, seja necessário cancelar os seus compromissos no dia seguinte, ou poderá precisar de ficar em vigilância durante 24 horas, embora esta situação seja raramente necessária."
  },
  ru: {
    med_title: "Медикаменты",
    med_desc: "• Приостановить прием Аспирина или других ингибиторов агрегации тромбоцитов, таких как Adiro®, Iscover®, Disgren®, Tiklid®, Plavix®, за 3-8 дней до исследования – проконсультируйтесь с врачом при сомнениях.\n• В случае приема Sintrom® или другого антикоагулянта (Xarelto®, Pradaxa®...), проконсультируйтесь с врачом для оценки его отмены или замены.\n• При сердечной патологии: Принесите электрокардиограмму, эхокардиограмму и указания вашего кардиолога. СООБЩИТЕ, ЕСЛИ ТРЕБУЕТСЯ АНТИБИОТИКОПРОФИЛАКТИКА.\n• Пероральное железо, отменить за 7 дней до колоноскопии.\n• НЕТ необходимости отменять другие лекарства – принимать до 12 часов до теста.",
    med_narrative: "Медикаменты. Вы должны приостановить прием Аспирина или других ингибиторов агрегации тромбоцитов, таких как Adiro, Iscover, Disgren, Tiklid или Plavix, за 3-8 дней до исследования. Проконсультируйтесь с врачом, если у вас есть сомнения. В случае приема Sintrom или другого антикоагулянта, такого как Xarelto или Pradaxa, вы должны проконсультироваться с врачом для оценки его отмены или замены. При сердечной патологии принесите электрокардиограмму, эхокардиограмму и указания вашего кардиолога. Сообщите, если требуется антибиотикопрофилактика. Пероральное железо необходимо отменить за 7 дней до колоноскопии. Нет необходимости отменять другие лекарства, вы можете принимать их до 12 часов до теста.",
    imp_title: "Важно",
    imp_desc: "• Не пейте алкоголь, молоко или что-либо красного или фиолетового цвета (например, ягодный сок) или другие напитки с мякотью.\n• Не ешьте во время приема Pleinvue® и до окончания клинической процедуры.\n• Вы не сможете водить машину в день колоноскопии или управлять опасными механизмами.\n• ПРИНЕСИТЕ ПОДПИСАННЫЕ СОГЛАСИЯ НА КОЛОНОСКОПИЮ И СЕДАЦИЮ.\n• Приходите на обследование в сопровождении человека, который сможет вести машину или помочь вам вернуться домой.\n• Существует вероятность того, что в случае терапевтических вмешательств, таких как удаление полипов, вам придется отменить свои планы на следующий день, или вам может потребоваться остаться под наблюдением на 24 часа (эта ситуация редко бывает необходимой).",
    imp_narrative: "Важно. Не пейте алкоголь, молоко или что-либо красного или фиолетового цвета, например, ягодный сок, или другие напитки с мякотью. Не ешьте во время приема Pleinvue и до окончания клинической процедуры. Вы не сможете водить машину в день колоноскопии или управлять опасными механизмами. Не забудьте принести подписанные согласия на колоноскопию и седацию. Приходите на обследование в сопровождении человека, который сможет вести машину или помочь вам вернуться домой. Существует вероятность того, что в случае терапевтических вмешательств, таких как удаление полипов, вам придется отменить свои планы на следующий день, или вам может потребоваться остаться под наблюдением на 24 часа, хотя эта ситуация редко бывает необходимой."
  },
  uk: {
    med_title: "Медикаменти",
    med_desc: "• Призупинити прийом Аспірину або інших інгібіторів агрегації тромбоцитів, таких як Adiro®, Iscover®, Disgren®, Tiklid®, Plavix®, за 3-8 днів до обстеження – проконсультуйтеся з лікарем при сумнівах.\n• У разі прийому Sintrom® або іншого антикоагулянту (Xarelto®, Pradaxa®...), проконсультуйтеся з лікарем для оцінки його відміни або заміни.\n• При серцевій патології: Принесіть електрокардіограму, ехокардіограму та вказівки вашого кардіолога. ПОВІДОМТЕ, ЯКЩО ПОТРІБНА АНТИБІОТИКОПРОФІЛАКТИКА.\n• Пероральне залізо, відмінити за 7 днів до колоноскопії.\n• НЕМАЄ необхідності відміняти інші ліки – приймати до 12 годин до тесту.",
    med_narrative: "Медикаменти. Ви повинні призупинити прийом Аспірину або інших інгібіторів агрегації тромбоцитів, таких як Adiro, Iscover, Disgren, Tiklid або Plavix, за 3-8 днів до обстеження. Проконсультуйтеся з лікарем, якщо у вас є сумніви. У разі прийому Sintrom або іншого антикоагулянту, такого як Xarelto або Pradaxa, ви повинні проконсультуватися з лікарем для оцінки його відміни або заміни. При серцевій патології принесіть електрокардіограму, ехокардіограму та вказівки вашого кардіолога. Повідомте, якщо потрібна антибіотикопрофілактика. Пероральне залізо необхідно відмінити за 7 днів до колоноскопії. Немає необхідності відміняти інші ліки, ви можете приймати їх до 12 годин до тесту.",
    imp_title: "Важливо",
    imp_desc: "• Не пийте алкоголь, молоко або будь-що червоного чи фіолетового кольору (наприклад, ягідний сік) або інші напої з м'якоттю.\n• Не їжте під час прийому Pleinvue® і до закінчення клінічної процедури.\n• Ви не зможете керувати автомобілем в день колоноскопії або керувати небезпечними механізмами.\n• ПРИНЕСІТЬ ПІДПИСАНІ ЗГОДИ НА КОЛОНОСКОПІЮ ТА СЕДАЦІЮ.\n• Приходьте на обстеження у супроводі людини, яка зможе вести машину або допомогти вам повернутися додому.\n• Існує ймовірність того, що у разі терапевтичних втручань, таких як видалення поліпів, вам доведеться скасувати свої плани на наступний день, або вам може знадобитися залишитися під наглядом на 24 години (ця ситуація рідко буває необхідною).",
    imp_narrative: "Важливо. Не пийте алкоголь, молоко або будь-що червоного чи фіолетового кольору, наприклад, ягідний сік, або інші напої з м'якоттю. Не їжте під час прийому Pleinvue і до закінчення клінічної процедури. Ви не зможете керувати автомобілем в день колоноскопії або керувати небезпечними механізмами. Не забудьте принести підписані згоди на колоноскопію та седацию. Приходьте на обстеження у супроводі людини, яка зможе вести машину або допомогти вам повернутися додому. Існує ймовірність того, що у разі терапевтичних втручань, таких як видалення поліпів, вам доведеться скасувати свої плани на наступний день, або вам може знадобитися залишитися під наглядом на 24 години, хоча ця ситуація рідко буває необхідною."
  },
  zh: {
    med_title: "药物",
    med_desc: "• 检查前 3 至 8 天暂停服用阿司匹林或其他血小板聚集抑制剂，如 Adiro®、Iscover®、Disgren®、Tiklid®、Plavix® – 如有疑问，请咨询您的医生。\n• 如果服用 Sintrom® 或其他抗凝剂（Xarelto®、Pradaxa®...），请咨询您的医生以评估其暂停或替代。\n• 如果您患有心脏病：请携带您的心电图、超声心动图和心脏病专家的指示。如果需要抗生素预防，请告知。\n• 口服铁剂，在结肠镜检查前 7 天暂停。\n• 不需要暂停其他药物 – 可以在检查前 12 小时服用。",
    med_narrative: "药物。您必须在检查前 3 至 8 天暂停服用阿司匹林或其他血小板聚集抑制剂，如 Adiro、Iscover、Disgren、Tiklid 或 Plavix。如有疑问，请咨询您的医生。如果您服用 Sintrom 或其他抗凝剂，如 Xarelto 或 Pradaxa，您必须咨询您的医生以评估其暂停或替代。如果您患有心脏病，请携带您的心电图、超声心动图和心脏病专家的指示。如果需要抗生素预防，请告知。口服铁剂必须在结肠镜检查前 7 天暂停。不需要暂停其他药物，您可以在检查前 12 小时服用。",
    imp_title: "重要",
    imp_desc: "• 不要饮酒、牛奶或任何红色或紫色的东西（例如浆果汁）或其他含有果肉的饮料。\n• 服用 Pleinvue® 期间直到临床程序结束后不要进食。\n• 结肠镜检查当天您将无法驾驶或操作危险机械。\n• 携带签署的结肠镜检查和镇静同意书。\n• 在可以驾驶或协助您回家的人的陪同下进行检查。\n• 如果进行治疗性干预（如息肉切除），您可能需要取消第二天的承诺，或者您可能需要留院观察 24 小时（这种情况很少需要）。",
    imp_narrative: "重要。不要饮酒、牛奶或任何红色或紫色的东西，例如浆果汁，或其他含有果肉的饮料。服用 Pleinvue 期间直到临床程序结束后不要进食。结肠镜检查当天您将无法驾驶或操作危险机械。记得携带签署的结肠镜检查和镇静同意书。在可以驾驶或协助您回家的人的陪同下进行检查。如果进行治疗性干预，如息肉切除，您可能需要取消第二天的承诺，或者您可能需要留院观察 24 小时，尽管这种情况很少需要。"
  },
  sv: {
    med_title: "Läkemedel",
    med_desc: "• Avbryt Aspirin eller andra trombocytaggregationshämmare som Adiro®, Iscover®, Disgren®, Tiklid®, Plavix® mellan 3 och 8 dagar före undersökningen – rådfråga din läkare om du är osäker.\n• Om du tar Sintrom® eller annat antikoagulantia (Xarelto®, Pradaxa®...) måste du rådfråga din läkare för att bedöma om det ska sättas ut eller bytas ut.\n• Vid hjärtsjukdom: Ta med ditt elektrokardiogram, ekokardiogram och din kardiologs anvisningar. MEDDELA OM ANTIBIOTIKAPROFYLAX KRÄVS.\n• Oralt järn, avbryt 7 dagar före koloskopin.\n• Det är INTE nödvändigt att avbryta andra mediciner – ta upp till 12 timmar före testet.",
    med_narrative: "Läkemedel. Du måste avbryta Aspirin eller andra trombocytaggregationshämmare som Adiro, Iscover, Disgren, Tiklid eller Plavix mellan 3 och 8 dagar före undersökningen. Rådfråga din läkare om du är osäker. Om du tar Sintrom eller annat antikoagulantia som Xarelto eller Pradaxa måste du rådfråga din läkare för att bedöma om det ska sättas ut eller bytas ut. Vid hjärtsjukdom, ta med ditt elektrokardiogram, ekokardiogram och din kardiologs anvisningar. Meddela om antibiotikaprofylax krävs. Oralt järn måste avbrytas 7 dagar före koloskopin. Det är inte nödvändigt att avbryta andra mediciner, du kan ta dem upp till 12 timmar före testet.",
    imp_title: "Viktigt",
    imp_desc: "• Drick inte alkohol, mjölk eller något rött eller lila (t.ex. bärjuice) eller andra drycker som innehåller fruktkött.\n• Ät inte medan du tar Pleinvue® och förrän efter det kliniska ingreppet.\n• Du kommer inte att kunna köra bil på dagen för koloskopin eller använda farliga maskiner.\n• TA MED DE UNDERTECKNADE SAMTYCKENA FÖR KOLOSKOPI OCH SEDERING.\n• Kom i sällskap till undersökningen med någon som kan köra eller hjälpa dig på hemresan.\n• Det finns en möjlighet att du vid terapeutiska ingrepp, såsom borttagning av polyper, kan behöva ställa in dina åtaganden nästa dag, eller så kan du behöva stanna för observation i 24 timmar (denna situation är sällan nödvändig).",
    imp_narrative: "Viktigt. Drick inte alkohol, mjölk eller något rött eller lila, såsom bärjuice, eller andra drycker som innehåller fruktkött. Ät inte medan du tar Pleinvue och förrän efter det kliniska ingreppet. Du kommer inte att kunna köra bil på dagen för koloskopin eller använda farliga maskiner. Kom ihåg att ta med de undertecknade samtyckena för koloskopi och sedering. Kom i sällskap till undersökningen med någon som kan köra eller hjälpa dig på hemresan. Det finns en möjlighet att du vid terapeutiska ingrepp, såsom borttagning av polyper, kan behöva ställa in dina åtaganden nästa dag, eller så kan du behöva stanna för observation i 24 timmar, även om denna situation sällan är nödvändig."
  },
  ar: {
    med_title: "الأدوية",
    med_desc: "• أوقف الأسبرين أو مثبطات تراكم الصفائح الدموية الأخرى مثل Adiro®، Iscover®، Disgren®، Tiklid®، Plavix® بين 3 و 8 أيام قبل الفحص - استشر طبيبك إذا كان لديك شك.\n• في حالة تناول Sintrom® أو مضاد تخثر آخر (Xarelto®، Pradaxa®...) يجب استشارة طبيبك لتقييم إيقافه أو استبداله.\n• في حالة الإصابة بأمراض القلب: أحضر مخطط كهربية القلب، مخطط صدى القلب وتعليمات طبيب القلب الخاص بك. أبلغ إذا كانت الوقاية بالمضادات الحيوية مطلوبة.\n• الحديد الفموي، أوقفه قبل 7 أيام من تنظير القولون.\n• ليس من الضروري إيقاف الأدوية الأخرى - تناولها حتى 12 ساعة قبل الاختبار.",
    med_narrative: "الأدوية. يجب إيقاف الأسبرين أو مثبطات تراكم الصفائح الدموية الأخرى مثل أديرا، إيسكوفر، ديسغرين، تيكليد، أو بلافيكس بين 3 و 8 أيام قبل الفحص. استشر طبيبك إذا كان لديك شك. في حالة تناول سينتروم أو مضاد تخثر آخر مثل زاريلتو أو براداكسا، يجب استشارة طبيبك لتقييم إيقافه أو استبداله. في حالة الإصابة بأمراض القلب، أحضر مخطط كهربية القلب، مخطط صدى القلب وتعليمات طبيب القلب الخاص بك. أبلغ إذا كانت الوقاية بالمضادات الحيوية مطلوبة. يجب إيقاف الحديد الفموي قبل 7 أيام من تنظير القولون. ليس من الضروري إيقاف الأدوية الأخرى، يمكنك تناولها حتى 12 ساعة قبل الاختبار.",
    imp_title: "هام",
    imp_desc: "• لا تشرب الكحول، الحليب، أو أي شيء أحمر أو أرجواني (على سبيل المثال، عصير التوت) أو المشروبات الأخرى التي تحتوي على اللب.\n• لا تأكل أثناء تناول Pleinvue® وحتى بعد الإجراء السريري.\n• لن تتمكن من القيادة في يوم تنظير القولون أو تشغيل الآلات الخطرة.\n• أحضر موافقات تنظير القولون والتخدير الموقعة.\n• تعال برفقة شخص إلى الفحص يمكنه القيادة أو مساعدتك في عودتك إلى المنزل.\n• هناك احتمال أنه في حالة التدخلات العلاجية، مثل إزالة السلائل، قد تحتاج إلى إلغاء التزاماتك في اليوم التالي، أو قد تحتاج إلى البقاء تحت المراقبة لمدة 24 ساعة (هذا الوضع نادرا ما يكون ضروريا).",
    imp_narrative: "هام. لا تشرب الكحول، الحليب، أو أي شيء أحمر أو أرجواني، مثل عصير التوت، أو المشروبات الأخرى التي تحتوي على اللب. لا تأكل أثناء تناول بلينفيو وحتى بعد الإجراء السريري. لن تتمكن من القيادة في يوم تنظير القولون أو تشغيل الآلات الخطرة. تذكر إحضار موافقات تنظير القولون والتخدير الموقعة. تعال برفقة شخص إلى الفحص يمكنه القيادة أو مساعدتك في عودتك إلى المنزل. هناك احتمال أنه في حالة التدخلات العلاجية، مثل إزالة السلائل، قد تحتاج إلى إلغاء التزاماتك في اليوم التالي، أو قد تحتاج إلى البقاء تحت المراقبة لمدة 24 ساعة، على الرغم من أن هذا الوضع نادرا ما يكون ضروريا."
  },
  no: {
    med_title: "Medisiner",
    med_desc: "• Avbryt Aspirin eller andre platehemmere som Adiro®, Iscover®, Disgren®, Tiklid®, Plavix® mellom 3 og 8 dager før undersøkelsen – kontakt legen din hvis du er i tvil.\n• Hvis du tar Sintrom® eller andre antikoagulantia (Xarelto®, Pradaxa®...), må du kontakte legen din for å vurdere om det skal seponeres eller byttes ut.\n• Ved hjertesykdom: Ta med EKG, ekkokardiogram og kardiologens instruksjoner. GI BESKJED HVIS ANTIBIOTIKAPROFYLAKSE ER NØDVENDIG.\n• Oralt jern, avbryt 7 dager før koloskopien.\n• Det er IKKE nødvendig å avbryte andre medisiner – ta inntil 12 timer før testen.",
    med_narrative: "Medisiner. Du må avbryte Aspirin eller andre platehemmere som Adiro, Iscover, Disgren, Tiklid eller Plavix mellom 3 og 8 dager før undersøkelsen. Kontakt legen din hvis du er i tvil. Hvis du tar Sintrom eller andre antikoagulantia som Xarelto eller Pradaxa, må du kontakte legen din for å vurdere om det skal seponeres eller byttes ut. Ved hjertesykdom, ta med EKG, ekkokardiogram og kardiologens instruksjoner. Gi beskjed hvis antibiotikaprofylakse er nødvendig. Oralt jern må avbrytes 7 dager før koloskopien. Det er ikke nødvendig å avbryte andre medisiner, du kan ta dem inntil 12 timer før testen.",
    imp_title: "Viktig",
    imp_desc: "• Ikke drikk alkohol, melk eller noe rødt eller lila (f.eks. bærjuice) eller andre drikker som inneholder fruktkjøtt.\n• Ikke spis mens du tar Pleinvue® og før etter den kliniske prosedyren.\n• Du vil ikke kunne kjøre bil på dagen for koloskopien eller betjene farlige maskiner.\n• TA MED SIGNERT SAMTYKKE FOR KOLOSKOPI OG SEDASJON.\n• Kom i følge til undersøkelsen med noen som kan kjøre eller hjelpe deg på hjemreisen.\n• Det er en mulighet for at du ved terapeutiske inngrep, som fjerning av polypper, kan måtte avlyse avtalene dine neste dag, eller du kan måtte bli til observasjon i 24 timer (denna situasjonen er sjelden nødvendig).",
    imp_narrative: "Viktig. Ikke drikk alkohol, melk eller noe rødt eller lila, som bærjuice, eller andre drikker som inneholder fruktkjøtt. Ikke spis mens du tar Pleinvue og før etter den kliniske prosedyren. Du vil ikke kunne kjøre bil på dagen for koloskopien eller betjene farlige maskiner. Husk å ta med signert samtykke for koloskopi og sedasjon. Kom i følge til undersøkelsen med noen som kan kjøre eller hjelpe deg på hjemreisen. Det er en mulighet for at du ved terapeutiske inngrep, som fjerning av polypper, kan måtte avlyse avtalene dine neste dag, eller du kan måtte bli til observasjon i 24 timer, selv om denne situasjonen sjelden er nødvendig."
  },
  be: {
    med_title: "Medicatie",
    med_desc: "• Stop met Aspirine of andere bloedplaatjesremmers zoals Adiro®, Iscover®, Disgren®, Tiklid®, Plavix® tussen 3 en 8 dagen voor het onderzoek – raadpleeg uw arts bij twijfel.\n• Als u Sintrom® of een ander antistollingsmiddel (Xarelto®, Pradaxa®...) gebruikt, moet u uw arts raadplegen om te beoordelen of het moet worden gestopt of vervangen.\n• Bij hartaandoeningen: Breng uw elektrocardiogram, echocardiogram en de instructies van uw cardioloog mee. MELD HET ALS ANTIBIOTICAPROFYLAXE VEREIST IS.\n• Oraal ijzer, stop 7 dagen voor de coloscopie.\n• Het is NIET nodig om andere medicijnen te stoppen – neem tot 12 uur voor de test in.",
    med_narrative: "Medicatie. U moet stoppen met Aspirine of andere bloedplaatjesremmers zoals Adiro, Iscover, Disgren, Tiklid of Plavix tussen 3 en 8 dagen voor het onderzoek. Raadpleeg uw arts bij twijfel. Als u Sintrom of een ander antistollingsmiddel zoals Xarelto of Pradaxa gebruikt, moet u uw arts raadplegen om te beoordelen of het moet worden gestopt of vervangen. Bij hartaandoeningen, breng uw elektrocardiogram, echocardiogram en de instructies van uw cardioloog mee. Meld het als antibioticaprofylaxe vereist is. Oraal ijzer moet 7 dagen voor de coloscopie worden gestopt. Het is niet nodig om andere medicijnen te stoppen, u kunt ze tot 12 uur voor de test innemen.",
    imp_title: "Belangrijk",
    imp_desc: "• Drink geen alcohol, melk of iets roods of paars (bijv. bessensap) of andere dranken die vruchtvlees bevatten.\n• Eet niet tijdens het innemen van Pleinvue® en tot na de klinische procedure.\n• U mag op de dag van de coloscopie niet autorijden of gevaarlijke machines bedienen.\n• BRENG DE ONDERTEKENDE TOESTEMMINGSFORMULIEREN VOOR COLOSCOPIE EN SEDATIE MEE.\n• Kom onder begeleiding naar het onderzoek met iemand die kan rijden of u kan helpen bij uw terugkeer naar huis.\n• Er is een mogelijkheid dat u bij therapeutische ingrepen, zoals het verwijderen van poliepen, uw afspraken de volgende dag moet annuleren, of dat u 24 uur ter observatie moet blijven (deze situatie is zelden nodig).",
    imp_narrative: "Belangrijk. Drink geen alcohol, melk of iets roods of paars, zoals bessensap, of andere dranken die vruchtvlees bevatten. Eet niet tijdens het innemen van Pleinvue en tot na de klinische procedure. U mag op de dag van de coloscopie niet autorijden of gevaarlijke machines bedienen. Vergeet niet de ondertekende toestemmingsformulieren voor coloscopie en sedatie mee te brengen. Kom onder begeleiding naar het onderzoek met iemand die kan rijden of u kan helpen bij uw terugkeer naar huis. Er is een mogelijkheid dat u bij therapeutische ingrepen, zoals het verwijderen van poliepen, uw afspraken de volgende dag moet annuleren, of dat u 24 uur ter observatie moet blijven, hoewel deze situatie zelden nodig is."
  },
  fi: {
    med_title: "Lääkitys",
    med_desc: "• Keskeytä Aspiriinin tai muiden verihiutaleiden estäjien, kuten Adiro®, Iscover®, Disgren®, Tiklid®, Plavix®, käyttö 3–8 päivää ennen tutkimusta – kysy lääkäriltäsi, jos olet epävarma.\n• Jos käytät Sintrom®-valmistetta tai muuta antikoagulanttia (Xarelto®, Pradaxa®...), sinun on neuvoteltava lääkärisi kanssa sen keskeyttämisestä tai korvaamisesta.\n• Sydänsairauksissa: Ota mukaan sydänsähkökäyrä, sydämen ultraäänitutkimus ja kardiologin ohjeet. ILMOITA, JOS ANTIBIOOTTIPROFYLAKSIA VAADITAAN.\n• Suun kautta otettava rauta, keskeytä 7 päivää ennen kolonoskopiaa.\n• Muiden lääkkeiden keskeyttäminen EI ole tarpeen – ota jopa 12 tuntia ennen testiä.",
    med_narrative: "Lääkitys. Sinun on keskeytettävä Aspiriinin tai muiden verihiutaleiden estäjien, kuten Adiron, Iscoverin, Disgrenin, Tiklidin tai Plavixin, käyttö 3–8 päivää ennen tutkimusta. Kysy lääkäriltäsi, jos olet epävarma. Jos käytät Sintromia tai muuta antikoagulanttia, kuten Xareltoa tai Pradaxaa, sinun on neuvoteltava lääkärisi kanssa sen keskeyttämisestä tai korvaamisesta. Sydänsairauksissa ota mukaan sydänsähkökäyrä, sydämen ultraäänitutkimus ja kardiologin ohjeet. Ilmoita, jos antibioottiprofylaksia vaaditaan. Suun kautta otettava rauta on keskeytettävä 7 päivää ennen kolonoskopiaa. Muiden lääkkeiden keskeyttäminen ei ole tarpeen, voit ottaa niitä jopa 12 tuntia ennen testiä.",
    imp_title: "Tärkeää",
    imp_desc: "• Älä juo alkoholia, maitoa tai mitään punaista tai violettia (esim. marjamehua) tai muita hedelmälihaa sisältäviä juomia.\n• Älä syö Pleinvue®-valmisteen ottamisen aikana ja ennen kuin kliinisen toimenpiteen jälkeen.\n• Et voi ajaa autoa kolonoskopiaklinikkapäivänä tai käyttää vaarallisia koneita.\n• TUO MUKANASI ALLEKIRJOITETUT SUOSTUMUKSET KOLONOSKOPIAAN JA RAUHOITUKSEEN.\n• Tule tutkimukseen saattajan kanssa, joka voi ajaa tai auttaa sinua kotimatkalla.\n• On mahdollista, että terapeuttisten toimenpiteiden, kuten polyyppien poiston, yhteydessä joudut perumaan seuraavan päivän menosi, tai saatat joutua jäämään tarkkailuun 24 tunniksi (tämä tilanne on harvoin tarpeen).",
    imp_narrative: "Tärkeää. Älä juo alkoholia, maitoa tai mitään punaista tai violettia, kuten marjamehua, tai muita hedelmälihaa sisältäviä juomia. Älä syö Pleinvue-valmisteen ottamisen aikana ja ennen kuin kliinisen toimenpiteen jälkeen. Et voi ajaa autoa kolonoskopiaklinikkapäivänä tai käyttää vaarallisia koneita. Muista tuoda mukanasi allekirjoitetut suostumukset kolonoskopiaan ja rauhoitukseen. Tule tutkimukseen saattajan kanssa, joka voi ajaa tai auttaa sinua kotimatkalla. On mahdollista, että terapeuttisten toimenpiteiden, kuten polyyppien poiston, yhteydessä joudut perumaan seuraavan päivän menosi, tai saatat joutua jäämään tarkkailuun 24 tunniksi, vaikka tämä tilanne on harvoin tarpeen."
  },
  nl: {
    med_title: "Medicatie",
    med_desc: "• Stop met Aspirine of andere bloedplaatjesremmers zoals Adiro®, Iscover®, Disgren®, Tiklid®, Plavix® tussen 3 en 8 dagen voor het onderzoek – raadpleeg uw arts bij twijfel.\n• Als u Sintrom® of een ander antistollingsmiddel (Xarelto®, Pradaxa®...) gebruikt, moet u uw arts raadplegen om te beoordelen of het moet worden gestopt of vervangen.\n• Bij hartaandoeningen: Breng uw elektrocardiogram, echocardiogram en de instructies van uw cardioloog mee. MELD HET ALS ANTIBIOTICAPROFYLAXE VEREIST IS.\n• Oraal ijzer, stop 7 dagen voor de coloscopie.\n• Het is NIET nodig om andere medicijnen te stoppen – neem tot 12 uur voor de test in.",
    med_narrative: "Medicatie. U moet stoppen met Aspirine of andere bloedplaatjesremmers zoals Adiro, Iscover, Disgren, Tiklid of Plavix tussen 3 en 8 dagen voor het onderzoek. Raadpleeg uw arts bij twijfel. Als u Sintrom of een ander antistollingsmiddel zoals Xarelto of Pradaxa gebruikt, moet u uw arts raadplegen om te beoordelen of het moet worden gestopt of vervangen. Bij hartaandoeningen, breng uw elektrocardiogram, echocardiogram en de instructies van uw cardioloog mee. Meld het als antibioticaprofylaxe vereist is. Oraal ijzer moet 7 dagen voor de coloscopie worden gestopt. Het is niet nodig om andere medicijnen te stoppen, u kunt ze tot 12 uur voor de test innemen.",
    imp_title: "Belangrijk",
    imp_desc: "• Drink geen alcohol, melk of iets roods of paars (bijv. bessensap) of andere dranken die vruchtvlees bevatten.\n• Eet niet tijdens het innemen van Pleinvue® en tot na de klinische procedure.\n• U mag op de dag van de coloscopie niet autorijden of gevaarlijke machines bedienen.\n• BRENG DE ONDERTEKENDE TOESTEMMINGSFORMULIEREN VOOR COLOSCOPIE EN SEDATIE MEE.\n• Kom onder begeleiding naar het onderzoek met iemand die kan rijden of u kan helpen bij uw terugkeer naar huis.\n• Er is een mogelijkheid dat u bij therapeutische ingrepen, zoals het verwijderen van poliepen, uw afspraken de volgende dag moet annuleren, of dat u 24 uur ter observatie moet blijven (deze situatie is zelden nodig).",
    imp_narrative: "Belangrijk. Drink geen alcohol, melk of iets roods of paars, zoals bessensap, of andere dranken die vruchtvlees bevatten. Eet niet tijdens het innemen van Pleinvue en tot na de klinische procedure. U mag op de dag van de coloscopie niet autorijden of gevaarlijke machines bedienen. Vergeet niet de ondertekende toestemmingsformulieren voor coloscopie en sedatie mee te brengen. Kom onder begeleiding naar het onderzoek met iemand die kan rijden of u kan helpen bij uw terugkeer naar huis. Er is een mogelijkheid dat u bij therapeutische ingrepen, zoals het verwijderen van poliepen, uw afspraken de volgende dag moet annuleren, of dat u 24 uur ter observatie moet blijven, hoewel deze situatie zelden nodig is."
  }
};

const langs = Object.keys(newTrans);

let newContent = content;

// Clean up the `es` block first
const transStart = newContent.indexOf('const TRANSLATIONS: Record<Language, Translation> = {');
const esBlockStart = newContent.indexOf('  es: {', transStart);
const enBlockStart = newContent.indexOf('  en: {', transStart);
let esBlock = newContent.substring(esBlockStart, enBlockStart);

// Remove all the extra screens from es
const allMedTitles = langs.map(l => newTrans[l].med_title);
const allImpTitles = langs.map(l => newTrans[l].imp_title);

for (const title of [...allMedTitles, ...allImpTitles]) {
  const regex = new RegExp(`\\{\\s*title:\\s*"\\s*${title}\\s*"[\\s\\S]*?\\},\\s*`, 'g');
  esBlock = esBlock.replace(regex, '');
}

// Remove all the extra narratives from es
const allMedNarratives = langs.map(l => newTrans[l].med_narrative);
const allImpNarratives = langs.map(l => newTrans[l].imp_narrative);

for (const narrative of [...allMedNarratives, ...allImpNarratives]) {
  // Escape special regex characters in narrative
  const escapedNarrative = narrative.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`"\\s*${escapedNarrative}\\s*",\\s*`, 'g');
  esBlock = esBlock.replace(regex, '');
}

newContent = newContent.substring(0, esBlockStart) + esBlock + newContent.substring(enBlockStart);

// Now iterate over all languages and insert correctly
for (let i = 0; i < langs.length; i++) {
  const lang = langs[i];
  const nextLang = i < langs.length - 1 ? langs[i+1] : null;
  
  const transStart = newContent.indexOf('const TRANSLATIONS: Record<Language, Translation> = {');
  const blockStart = newContent.indexOf(`  ${lang}: {`, transStart);
  const blockEnd = nextLang ? newContent.indexOf(`  ${nextLang}: {`, transStart) : newContent.indexOf('};\n\n// --- Helper Functions ---');
  
  if (blockStart === -1 || blockEnd === -1) continue;
  
  let block = newContent.substring(blockStart, blockEnd);
  
  const trans = newTrans[lang];
  
  // Clean up any existing ones just in case
  block = block.replace(new RegExp(`\\{\\s*title:\\s*"${trans.med_title}"[\\s\\S]*?\\},\\s*`, 'g'), '');
  block = block.replace(new RegExp(`\\{\\s*title:\\s*"${trans.imp_title}"[\\s\\S]*?\\},\\s*`, 'g'), '');
  
  const escapedMedNarrative = trans.med_narrative.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const escapedImpNarrative = trans.imp_narrative.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  
  block = block.replace(new RegExp(`"${escapedMedNarrative}",\\s*`, 'g'), '');
  block = block.replace(new RegExp(`"${escapedImpNarrative}",\\s*`, 'g'), '');
  
  // Add Medication at the beginning of screens
  const screensStart = block.indexOf('screens: [') + 'screens: ['.length;
  const medScreen = `\n      { title: "${trans.med_title}", description: ${JSON.stringify(trans.med_desc)}, prompt: "A medical infographic showing medication instructions." },`;
  block = block.substring(0, screensStart) + medScreen + block.substring(screensStart);
  
  // Add Important before the last screen
  const screensEnd = block.indexOf('    ],\n    narrative: [');
  const lastScreenStart = block.lastIndexOf('{', screensEnd);
  const impScreen = `{ title: "${trans.imp_title}", description: ${JSON.stringify(trans.imp_desc)}, prompt: "A medical infographic showing important instructions." },\n      `;
  block = block.substring(0, lastScreenStart) + impScreen + block.substring(lastScreenStart);
  
  // Add Medication narrative at the beginning of narrative
  const narrativeStart = block.indexOf('narrative: [') + 'narrative: ['.length;
  const medNarrative = `\n      ${JSON.stringify(trans.med_narrative)},`;
  block = block.substring(0, narrativeStart) + medNarrative + block.substring(narrativeStart);
  
  // Add Important narrative before the last narrative
  const narrativeEnd = block.lastIndexOf('    ]\n  }');
  const lastNarrativeStart = block.lastIndexOf('"', block.lastIndexOf('"', narrativeEnd) - 1);
  const impNarrative = `${JSON.stringify(trans.imp_narrative)},\n      `;
  block = block.substring(0, lastNarrativeStart) + impNarrative + block.substring(lastNarrativeStart);
  
  newContent = newContent.substring(0, blockStart) + block + newContent.substring(blockEnd);
}

// Update STATIC_IMAGES
const staticImagesRegex = /const STATIC_IMAGES: Record<number, string> = {[\s\S]*?};/;
const newStaticImages = `const STATIC_IMAGES: Record<number, string> = {
  0: '/Dieta-sin-fibra-2.png',
  1: '/Infografia-general-preparacion.png',
  2: '/Dieta-sin-fibra-2.png',
  3: '/Dieta-liquidos.png',
  4: '/Caja-de-Pleinvue.png',
  5: '/Pleinvue-1ra-dosis.png',
  6: '/Infografia-general-preparacion.png',
  7: '/Pleinvue-2da-dosis.png',
  8: '/Infografia-general-preparacion.png',
  9: '/Infografia-general-preparacion.png',
  10: '/dr-nardulli.png'
};`;

newContent = newContent.replace(staticImagesRegex, newStaticImages);

fs.writeFileSync('./src/App.tsx', newContent);
console.log('Fixed App.tsx');